version: '3'
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: "db_user"
      POSTGRES_PASSWORD: "12345678"
      POSTGRES_DB: "crypto_tracker"
    volumes:
      - db-data:/var/lib/postgresql/data
  coinnews:
    image: amirhossein21/coinnews.macos:v0.2
    ports:
      - "8080:8080"
    volumes:
      - ./coinnews/config.yml:/go/src/app/config.yml
  bepa:
    build:
      context: .
      dockerfile: Dockerfile.bepa
    restart: always
    depends_on:
      - db
      - coinnews
    environment:
      POSTGRES_USER: "db_user"
      POSTGRES_PASSWORD: "12345678"
      POSTGRES_HOST: "db"

  peyk:
    build:
      context: .
      dockerfile: Dockerfile.peyk
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: "db_user"
      POSTGRES_PASSWORD: "12345678"
      POSTGRES_HOST: "db"

volumes:
  db-data:
