apiVersion: batch/v1
kind: CronJob
metadata:
  name: myapp-cron
spec:
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: myapp-cron
            image: msalehiv/bepa-service
            envFrom:
            - configMapRef:
                name: myapp-config
            - secretRef:
                name: db-secret
          restartPolicy: OnFailure
