apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  POSTGRES_USER: "db_user"
  POSTGRES_PASSWORD: "12345678"
  POSTGRES_HOST: "db"
  MAILGUN_API_KEY: "somekey"
  MAILGUN_DOMAIN_NAME: "somedomain"
